### ISSUE TITLE
Unsure of what the package is doing

### ISSUE THREAD

**Issue by JosephTLyons** [EvanHahn/atom-language-brainfuck#5]
Hello Evan,

I'm a bit unfamiliar with the Atom package system for languages, so this is most likely ignorance on my part, but I'm not quire sure what this package is doing.  I downloaded it and I'm not really noticing a difference between having it enabled and having it disabled.  I notice it has a settings panel, as the other language packages do, so is the point of the package to have language-specific settings?  or does it offer something else that I am missing?

**Comment by EvanHahn** [comment]
I haven't used it in awhile, but it should do syntax highlighting for Brainfuck programs. Are you not seeing that?

**Comment by JosephTLyons** [comment]
Ok yeah, I'm seeing it now.  I believe I had the package installed before the first time I opened a .bf file on my comp.  So when I ran it, the syntax highlighting was there to begin with.  Disabling didn't do anything, like shut of the syntax highlighting, but that is because I didn't restart Atom to "seat" the effect of disabling it.  So yes, syntax highlighting is working.  My apologies.

**Comment by EvanHahn** [comment]
No worries!

Do you mind if I close this issue?

**Comment by JosephTLyons** [comment]
Yep, all is good on my end, go ahead and close it.

**Comment by EvanHahn** [comment]
Closed it. Feel free to open a new issue should anything come up!
